# Generated by Django 5.0.8 on 2024-08-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grading',
            name='unique_user_data',
        ),
    ]
