# Generated by Django 5.0.8 on 2024-08-14 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_grading_unique_user_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grading',
            constraint=models.UniqueConstraint(fields=('user', 'used_standard'), name='unique_user_data'),
        ),
    ]
