# Generated by Django 5.0.8 on 2024-08-15 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_grading_unique_user_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grading',
            options={'verbose_name': 'Оценивание'},
        ),
        migrations.AlterField(
            model_name='grading',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grading',
            name='used_standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.criteria'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
