# Generated by Django 5.0.8 on 2024-08-27 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_grading_options_alter_grading_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должности',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.AlterModelOptions(
            name='criteria',
            options={'verbose_name': 'Работы и нормативы', 'verbose_name_plural': 'Работы и нормативы'},
        ),
        migrations.AlterModelOptions(
            name='grading',
            options={'verbose_name': 'Выполненные работы', 'verbose_name_plural': 'Выполненные работы'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Рейтинг работников', 'verbose_name_plural': 'Рейтинг работников'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Названия таблиц', 'verbose_name_plural': 'Названия таблиц'},
        ),
        migrations.AlterField(
            model_name='criteria',
            name='standard_in_points',
            field=models.CharField(max_length=30, verbose_name='Норматив в баллах'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='table_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.table', verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Наименование работ'),
        ),
        migrations.AlterField(
            model_name='grading',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='grading',
            name='used_standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.criteria', verbose_name='Наименование работ'),
        ),
        migrations.AlterField(
            model_name='grading',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер'),
        ),
        migrations.AlterField(
            model_name='grading',
            name='work_done',
            field=models.CharField(blank=True, max_length=400, verbose_name='Выполненная работа'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ratings',
            field=models.PositiveIntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table',
            field=models.CharField(max_length=50, verbose_name='Название таблицы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.positions', verbose_name='Должность'),
        ),
    ]
