# Generated by Django 5.0.8 on 2024-08-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_positions_alter_criteria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='status',
            field=models.CharField(choices=[('not_checked', 'Не проверено'), ('approved', 'Одобрено'), ('has_errors', 'Есть ошибки')], default='not_checked', max_length=20),
        ),
    ]
