# Generated by Django 5.0.8 on 2024-08-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_grading_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': 'Отделы', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterField(
            model_name='grading',
            name='status',
            field=models.CharField(choices=[('not_checked', 'Не проверено'), ('approved', 'Одобрено'), ('has_errors', 'Есть ошибки')], default='not_checked', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='position_name',
            field=models.CharField(max_length=50, verbose_name='Отдел'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ManyToManyField(blank=True, to='main_app.positions', verbose_name='Отдел'),
        ),
    ]
