# Generated by Django 5.0.8 on 2024-09-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_cathedras_faculties_remove_profile_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectors',
            name='audited_faculty',
        ),
        migrations.AddField(
            model_name='inspectors',
            name='audited_faculty',
            field=models.ManyToManyField(to='main_app.faculties', verbose_name='Факультеты'),
        ),
    ]
